SET allow_system_table_mods = off;
CREATE TABLE pg_catalog.test (a int);
CREATE TABLE t1x (a int, b anyarray);
ALTER TABLE pg_namespace ADD CONSTRAINT foo UNIQUE USING INDEX pg_namespace_nspname_index;
INSERT INTO pg_description (objoid, classoid, objsubid, description) VALUES (0, 0, 0, 'foo');
INSERT INTO pg_description (objoid, classoid, objsubid, description) VALUES (0, 0, 1, 'foo');
DROP TABLE pg_description;
TRUNCATE pg_description;
ALTER TABLE pg_description RENAME COLUMN description TO comment;
ALTER TABLE pg_description ALTER COLUMN description SET NOT NULL;
ALTER TABLE pg_description ALTER COLUMN description SET STATISTICS -1;
CREATE TABLE foo (a oid, b oid, c int, FOREIGN KEY (a, b, c) REFERENCES pg_description);
CREATE INDEX pg_description_test_index ON pg_description (description);
ALTER TABLE pg_description RENAME TO pg_comment;
ALTER TABLE pg_description SET SCHEMA public;
