SET allow_system_table_mods = on;
DROP TABLE pg_description;
BEGIN;
TRUNCATE pg_description;
ROLLBACK;
BEGIN;
ALTER TABLE pg_description RENAME COLUMN description TO comment;
ROLLBACK;
BEGIN;
ALTER TABLE pg_description ALTER COLUMN description SET NOT NULL;
ROLLBACK;
BEGIN;
ALTER TABLE pg_description ALTER COLUMN description SET STATISTICS -1;
ROLLBACK;
BEGIN;
CREATE TABLE foo (a oid, b oid, c int, FOREIGN KEY (a, b, c) REFERENCES pg_description);
ROLLBACK;
BEGIN;
CREATE INDEX pg_description_test_index ON pg_description (description);
ROLLBACK;
BEGIN;
ALTER TABLE pg_description RENAME TO pg_comment;
ROLLBACK;
BEGIN;
ALTER TABLE pg_description SET SCHEMA public;
ROLLBACK;
